apiVersion: v1
kind: Template
metadata:
  name: buildconfigs-origin-metrics
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: java-jdk
  spec:
    dockerImageRepository: jboss/base-jdk
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: wildfly
  spec:
    dockerImageRepository: jboss/wildfly
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: heapster
  spec:
    dockerImageRepository: openshift/origin-metrics-heapster-base
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: openshift-origin
  spec:
    dockerImageRepository: openshift/origin
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: metrics-deployer
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: metrics-hawkular-metrics
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: metrics-cassandra
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: metrics-heapster
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: metrics-schema-installer
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: metrics-deployer
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: metrics-deployer:${DEPLOYER_IMAGE_TAG}
    source:
      contextDir: deployer
      git:
        uri: ${GIT_URI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: openshift-origin:${ORIGIN_IMAGE_TAG}
      type: Docker
    triggers:
    - github:
        secret: ${TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${TRIGGER_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: metrics-hawkular-metrics
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: metrics-hawkular-metrics:${IMAGE_TAG}
    source:
      contextDir: hawkular-metrics
      git:
        uri: ${GIT_URI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: wildfly:latest
      type: Docker
    triggers:
    - github:
        secret: ${TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${TRIGGER_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: metrics-cassandra
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: metrics-cassandra:${IMAGE_TAG}
    source:
      contextDir: cassandra
      git:
        uri: ${GIT_URI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: java-jdk:8
      type: Docker
    triggers:
    - github:
        secret: ${TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${TRIGGER_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: metrics-heapster
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: metrics-heapster:${IMAGE_TAG}
    source:
      contextDir: heapster
      git:
        uri: ${GIT_URI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: heapster:latest
      type: Docker
    triggers:
    - github:
        secret: ${TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${TRIGGER_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: metrics-schema-installer
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: metrics-schema-installer:${IMAGE_TAG}
    source:
      contextDir: schema-installer
      git:
        uri: ${GIT_URI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: java-jdk:8
      type: Docker
    triggers:
    - github:
        secret: ${TRIGGER_SECRET}
      type: GitHub
    - generic:
        secret: ${TRIGGER_SECRET}
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: Secret for buildconfig triggers
  from: '[a-zA-Z0-9]{8}'
  generate: expression
  name: TRIGGER_SECRET
  required: true
- description: Repo prefix for the metrics components (e.g. openshift/origin-)
  name: IMAGE_PREFIX
  required: true
  value: docker.io/openshift/origin-
- description: Tag to use for the metrics components
  name: IMAGE_TAG
  required: true
  value: latest
- description: Origin tag to use
  name: ORIGIN_IMAGE_TAG
  required: true
  value: latest
- description: Deployer tag to use
  name: DEPLOYER_IMAGE_TAG
  required: true
  value: latest
- description: git source uri
  name: GIT_URI
  required: true
  value: https://github.com/openshift/origin-metrics.git
